name: homapy
channels:
  - conda-forge  
dependencies:
  - python=3.11
  - pip
  - cmake>=3.24  
  - numpy
  - scipy    
  - pytest
  - pip:
      - scikit-build-core>=0.12
      - nanobind>=2.2      
      # - cupy-cuda12x
